### ISSUE TITLE
No module named 'chanspec'

### ISSUE THREAD

**Issue by fallen** [wking/pycomedi#1]
Hi, 
I got this while trying to use pycomedi on Debian Jessie with Python 3.4
Python 3.4.2 (default, Oct  8 2014, 13:14:40) 
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.

> > > from pycomedi.device import Device
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "pycomedi/instruction.pxd", line 22, in init pycomedi.device (pycomedi/device.c:5065)
> > >   File "pycomedi/instruction.pyx", line 25, in init pycomedi.instruction (pycomedi/instruction.c:2605)
> > > ImportError: No module named 'chanspec'

Here is the log of when I installed pycomedi:

yann@pcqu1r0x:~/dev/pycomedi$ sudo python3.4 ./setup.py install
running install
running build
running build_py
running build_ext
skipping 'pycomedi/_error.c' Cython extension (up-to-date)
building 'pycomedi._error' extension
i586-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/local/lib/python3.4/dist-packages/numpy/core/include -I/usr/include/python3.4m -c pycomedi/_error.c -o build/temp.linux-i686-3.4/pycomedi/_error.o
pycomedi/_error.c: In function ‘__pyx_pf_8pycomedi_6_error_raise_error’:
pycomedi/_error.c:1022:22: warning: assignment discards ‘const’ qualifier from pointer target type
   __pyx_v_comedi_msg = comedi_strerror(__pyx_v_errno);
                      ^
i586-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 build/temp.linux-i686-3.4/pycomedi/_error.o -lcomedi -o build/lib.linux-i686-3.4/pycomedi/_error.cpython-34m.so
cythoning pycomedi/calibration.pyx to pycomedi/calibration.c
building 'pycomedi.calibration' extension
i586-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/local/lib/python3.4/dist-packages/numpy/core/include -I/usr/include/python3.4m -c pycomedi/calibration.c -o build/temp.linux-i686-3.4/pycomedi/calibration.o
In file included from /usr/local/lib/python3.4/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1804:0,
                 from /usr/local/lib/python3.4/dist-packages/numpy/core/include/numpy/ndarrayobject.h:17,
                 from /usr/local/lib/python3.4/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from pycomedi/calibration.c:241:
/usr/local/lib/python3.4/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
In file included from /usr/local/lib/python3.4/dist-packages/numpy/core/include/numpy/ndarrayobject.h:26:0,
                 from /usr/local/lib/python3.4/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from pycomedi/calibration.c:241:
/usr/local/lib/python3.4/dist-packages/numpy/core/include/numpy/__multiarray_api.h:1629:1: warning: ‘_import_array’ defined but not used [-Wunused-function]
 _import_array(void)
 ^
In file included from /usr/local/lib/python3.4/dist-packages/numpy/core/include/numpy/ufuncobject.h:317:0,
                 from pycomedi/calibration.c:242:
/usr/local/lib/python3.4/dist-packages/numpy/core/include/numpy/__ufunc_api.h:241:1: warning: ‘_import_umath’ defined but not used [-Wunused-function]
 _import_umath(void)
 ^
i586-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 build/temp.linux-i686-3.4/pycomedi/calibration.o -lcomedi -o build/lib.linux-i686-3.4/pycomedi/calibration.cpython-34m.so
cythoning pycomedi/channel.pyx to pycomedi/channel.c
building 'pycomedi.channel' extension
i586-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/local/lib/python3.4/dist-packages/numpy/core/include -I/usr/include/python3.4m -c pycomedi/channel.c -o build/temp.linux-i686-3.4/pycomedi/channel.o
In file included from /usr/local/lib/python3.4/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1804:0,
                 from /usr/local/lib/python3.4/dist-packages/numpy/core/include/numpy/ndarrayobject.h:17,
                 from /usr/local/lib/python3.4/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from pycomedi/channel.c:239:
/usr/local/lib/python3.4/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
In file included from /usr/local/lib/python3.4/dist-packages/numpy/core/include/numpy/ndarrayobject.h:26:0,
                 from /usr/local/lib/python3.4/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from pycomedi/channel.c:239:
/usr/local/lib/python3.4/dist-packages/numpy/core/include/numpy/__multiarray_api.h:1629:1: warning: ‘_import_array’ defined but not used [-Wunused-function]
 _import_array(void)
 ^
In file included from /usr/local/lib/python3.4/dist-packages/numpy/core/include/numpy/ufuncobject.h:317:0,
                 from pycomedi/channel.c:240:
/usr/local/lib/python3.4/dist-packages/numpy/core/include/numpy/__ufunc_api.h:241:1: warning: ‘_import_umath’ defined but not used [-Wunused-function]
 _import_umath(void)
 ^
i586-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 build/temp.linux-i686-3.4/pycomedi/channel.o -lcomedi -o build/lib.linux-i686-3.4/pycomedi/channel.cpython-34m.so
cythoning pycomedi/chanspec.pyx to pycomedi/chanspec.c
building 'pycomedi.chanspec' extension
i586-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/local/lib/python3.4/dist-packages/numpy/core/include -I/usr/include/python3.4m -c pycomedi/chanspec.c -o build/temp.linux-i686-3.4/pycomedi/chanspec.o
i586-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 build/temp.linux-i686-3.4/pycomedi/chanspec.o -lcomedi -o build/lib.linux-i686-3.4/pycomedi/chanspec.cpython-34m.so
cythoning pycomedi/command.pyx to pycomedi/command.c
building 'pycomedi.command' extension
i586-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/local/lib/python3.4/dist-packages/numpy/core/include -I/usr/include/python3.4m -c pycomedi/command.c -o build/temp.linux-i686-3.4/pycomedi/command.o
i586-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 build/temp.linux-i686-3.4/pycomedi/command.o -lcomedi -o build/lib.linux-i686-3.4/pycomedi/command.cpython-34m.so
cythoning pycomedi/constant.pyx to pycomedi/constant.c
building 'pycomedi.constant' extension
i586-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/local/lib/python3.4/dist-packages/numpy/core/include -I/usr/include/python3.4m -c pycomedi/constant.c -o build/temp.linux-i686-3.4/pycomedi/constant.o
i586-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 build/temp.linux-i686-3.4/pycomedi/constant.o -lcomedi -o build/lib.linux-i686-3.4/pycomedi/constant.cpython-34m.so
cythoning pycomedi/device.pyx to pycomedi/device.c
building 'pycomedi.device' extension
i586-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/local/lib/python3.4/dist-packages/numpy/core/include -I/usr/include/python3.4m -c pycomedi/device.c -o build/temp.linux-i686-3.4/pycomedi/device.o
pycomedi/device.c: In function ‘__pyx_pf_8pycomedi_6device_6Device_16get_driver_name’:
pycomedi/device.c:2060:15: warning: assignment discards ‘const’ qualifier from pointer target type
   __pyx_v_ret = comedi_get_driver_name(__pyx_v_self->__pyx_base.device);
               ^
pycomedi/device.c: In function ‘__pyx_pf_8pycomedi_6device_6Device_18get_board_name’:
pycomedi/device.c:2193:15: warning: assignment discards ‘const’ qualifier from pointer target type
   __pyx_v_ret = comedi_get_board_name(__pyx_v_self->__pyx_base.device);
               ^
i586-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 build/temp.linux-i686-3.4/pycomedi/device.o -lcomedi -o build/lib.linux-i686-3.4/pycomedi/device.cpython-34m.so
cythoning pycomedi/device_holder.pyx to pycomedi/device_holder.c
building 'pycomedi.device_holder' extension
i586-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/local/lib/python3.4/dist-packages/numpy/core/include -I/usr/include/python3.4m -c pycomedi/device_holder.c -o build/temp.linux-i686-3.4/pycomedi/device_holder.o
i586-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 build/temp.linux-i686-3.4/pycomedi/device_holder.o -lcomedi -o build/lib.linux-i686-3.4/pycomedi/device_holder.cpython-34m.so
cythoning pycomedi/instruction.pyx to pycomedi/instruction.c
building 'pycomedi.instruction' extension
i586-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/local/lib/python3.4/dist-packages/numpy/core/include -I/usr/include/python3.4m -c pycomedi/instruction.c -o build/temp.linux-i686-3.4/pycomedi/instruction.o
i586-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 build/temp.linux-i686-3.4/pycomedi/instruction.o -lcomedi -o build/lib.linux-i686-3.4/pycomedi/instruction.cpython-34m.so
cythoning pycomedi/library.pyx to pycomedi/library.c
building 'pycomedi.library' extension
i586-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/local/lib/python3.4/dist-packages/numpy/core/include -I/usr/include/python3.4m -c pycomedi/library.c -o build/temp.linux-i686-3.4/pycomedi/library.o
i586-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 build/temp.linux-i686-3.4/pycomedi/library.o -lcomedi -o build/lib.linux-i686-3.4/pycomedi/library.cpython-34m.so
cythoning pycomedi/range.pyx to pycomedi/range.c
building 'pycomedi.range' extension
i586-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/local/lib/python3.4/dist-packages/numpy/core/include -I/usr/include/python3.4m -c pycomedi/range.c -o build/temp.linux-i686-3.4/pycomedi/range.o
i586-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 build/temp.linux-i686-3.4/pycomedi/range.o -lcomedi -o build/lib.linux-i686-3.4/pycomedi/range.cpython-34m.so
cythoning pycomedi/subdevice.pyx to pycomedi/subdevice.c
building 'pycomedi.subdevice' extension
i586-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/local/lib/python3.4/dist-packages/numpy/core/include -I/usr/include/python3.4m -c pycomedi/subdevice.c -o build/temp.linux-i686-3.4/pycomedi/subdevice.o
i586-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 build/temp.linux-i686-3.4/pycomedi/subdevice.o -lcomedi -o build/lib.linux-i686-3.4/pycomedi/subdevice.cpython-34m.so
cythoning pycomedi/subdevice_holder.pyx to pycomedi/subdevice_holder.c
building 'pycomedi.subdevice_holder' extension
i586-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/local/lib/python3.4/dist-packages/numpy/core/include -I/usr/include/python3.4m -c pycomedi/subdevice_holder.c -o build/temp.linux-i686-3.4/pycomedi/subdevice_holder.o
i586-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 build/temp.linux-i686-3.4/pycomedi/subdevice_holder.o -lcomedi -o build/lib.linux-i686-3.4/pycomedi/subdevice_holder.cpython-34m.so
running install_lib
creating /usr/local/lib/python3.4/dist-packages/pycomedi
copying build/lib.linux-i686-3.4/pycomedi/device.cpython-34m.so -> /usr/local/lib/python3.4/dist-packages/pycomedi
copying build/lib.linux-i686-3.4/pycomedi/instruction.cpython-34m.so -> /usr/local/lib/python3.4/dist-packages/pycomedi
copying build/lib.linux-i686-3.4/pycomedi/calibration.cpython-34m.so -> /usr/local/lib/python3.4/dist-packages/pycomedi
copying build/lib.linux-i686-3.4/pycomedi/subdevice_holder.cpython-34m.so -> /usr/local/lib/python3.4/dist-packages/pycomedi
copying build/lib.linux-i686-3.4/pycomedi/__init__.py -> /usr/local/lib/python3.4/dist-packages/pycomedi
copying build/lib.linux-i686-3.4/pycomedi/channel.cpython-34m.so -> /usr/local/lib/python3.4/dist-packages/pycomedi
copying build/lib.linux-i686-3.4/pycomedi/subdevice.cpython-34m.so -> /usr/local/lib/python3.4/dist-packages/pycomedi
copying build/lib.linux-i686-3.4/pycomedi/_error.cpython-34m.so -> /usr/local/lib/python3.4/dist-packages/pycomedi
copying build/lib.linux-i686-3.4/pycomedi/utility.py -> /usr/local/lib/python3.4/dist-packages/pycomedi
copying build/lib.linux-i686-3.4/pycomedi/library.cpython-34m.so -> /usr/local/lib/python3.4/dist-packages/pycomedi
copying build/lib.linux-i686-3.4/pycomedi/chanspec.cpython-34m.so -> /usr/local/lib/python3.4/dist-packages/pycomedi
copying build/lib.linux-i686-3.4/pycomedi/device_holder.cpython-34m.so -> /usr/local/lib/python3.4/dist-packages/pycomedi
copying build/lib.linux-i686-3.4/pycomedi/command.cpython-34m.so -> /usr/local/lib/python3.4/dist-packages/pycomedi
copying build/lib.linux-i686-3.4/pycomedi/range.cpython-34m.so -> /usr/local/lib/python3.4/dist-packages/pycomedi
copying build/lib.linux-i686-3.4/pycomedi/constant.cpython-34m.so -> /usr/local/lib/python3.4/dist-packages/pycomedi
byte-compiling /usr/local/lib/python3.4/dist-packages/pycomedi/__init__.py to **init**.cpython-34.pyc
byte-compiling /usr/local/lib/python3.4/dist-packages/pycomedi/utility.py to utility.cpython-34.pyc
running install_egg_info
Writing /usr/local/lib/python3.4/dist-packages/pycomedi-0.8.egg-info

Thanks!

**Comment by wking** [comment]
On Mon, Jan 12, 2015 at 12:09:57PM -0800, Yann Sionneau wrote:

> ImportError: No module named 'chanspec'

Ah, that was a relative-import issue [1](https://groups.google.com/forum/#!topic/comedi_list/5qo3u_Qjx2Q).  I'd worked up a fix in a
branch, but forgotten to merge and release the fix.  Done now as v0.9
[2](https://pypi.python.org/pypi/pycomedi/0.9).  Please re-open this issue if that doesn't fix it for you.
